# Generated by Django 6.0.6 on 2026-08-07 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('ollama', 'Ollama')], max_length=20)),
                ('model_id', models.CharField(help_text='e.g. gpt-4o-mini, claude-sonnet-4-6', max_length=100)),
                ('api_key', models.CharField(blank=True, help_text='Leave blank to use environment variable', max_length=500)),
                ('base_url', models.URLField(blank=True, help_text='Required for Ollama (e.g. http://localhost:11434)')),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('system_prompt_prefix', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Model',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Shown to the LLM as the tool description')),
                ('tool_type', models.CharField(choices=[('built_in', 'Built-in'), ('llm_subagent', 'LLM Subagent'), ('custom_python', 'Custom Python')], default='built_in', max_length=20)),
                ('implementation', models.CharField(blank=True, help_text='Dotted Python path for built_in/custom tools (e.g. llm_admin.builtin_tools.web_search.run)', max_length=300)),
                ('parameters_schema', models.JSONField(default=dict, help_text="OpenAI function-calling JSON schema for this tool's inputs")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_model', models.ForeignKey(blank=True, help_text='Populated only when tool_type=llm_subagent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subagent_tools', to='llm_admin.llmmodel')),
            ],
            options={
                'verbose_name': 'Tool',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLMModelTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_assignments', to='llm_admin.llmmodel')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_assignments', to='llm_admin.tool')),
            ],
            options={
                'verbose_name': 'Model-Tool Assignment',
                'ordering': ['priority'],
                'unique_together': {('llm_model', 'tool')},
            },
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='llm_models', through='llm_admin.LLMModelTool', to='llm_admin.tool'),
        ),
    ]
