# Generated by Django 6.0.6 on 2026-06-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_chatsession_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
