# Generated by Django 6.0.6 on 2026-06-13 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_add_session_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_message', models.TextField()),
                ('symptoms_detected', models.JSONField(default=list)),
                ('guidance_given', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to='patient.patient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to='patient.chatsession')),
            ],
            options={
                'db_table': 'emergency_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
