# Generated by Django 6.0.6 on 2026-06-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_add_emergency_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
