# Generated by Django 6.0.6 on 2026-06-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_add_doctor_note'),
        ('patient', '0006_add_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to='doctor.doctor'),
        ),
    ]
