# Generated by Django 6.0.6 on 2026-08-12 01:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_add_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='conversation_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='is_summarized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='patient.chatsession')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
    ]
