# Generated by Django 6.0.6 on 2026-06-21 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('emergency_medicine', 'Emergency Medicine'), ('internal_medicine', 'Internal Medicine'), ('psychiatry', 'Psychiatry'), ('other', 'Other')], default='general_practice', max_length=50)),
                ('license_number', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'doctors',
            },
            bases=('users.user',),
        ),
    ]
