# Generated by Django 6.0.6 on 2026-06-21 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0005_add_session_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='doctor.doctor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='patient.chatsession')),
            ],
            options={
                'db_table': 'doctor_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
